// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  picture: dynamic(() => import("./Picture")),
  rich_text: dynamic(() => import("./RichText")),
};
